# Generated by Django 4.2.7 on 2023-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_kyc_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default=None, max_length=255, null=True, upload_to='kyc'),
        ),
    ]
